### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by Fouad1806** [fabrice-eberle/mpt_faces_fab_fou_til#2]
The identified faces need to be cropped based on the saved coordinates in a seperate file. The cropped images will be saved in a folder which is named after the object (human) that was recorded.

**Comment by fabrice-eberle** [comment]
The issue was closed by the first merge. Images are cropped without the frame. Also a mirrored frame was added.

**Comment by fabrice-eberle** [comment]
#3
